name: buildroot-mender

services:
  buildroot-mender:
    build:
      context: ./
      args:
        BUILDROOT_USER: br-user
        BUILDROOT_DIR: buildroot
        BUILDROOT_VERSION: 2025.02.4
        # BUILDROOT_BRANCH: master
        # BUILDROOT_COMMIT: 00d5d387f5b9be4398af4c684150785896ee7b7c
        # Space deliminated list of external trees of which to use.
        EXTERNAL_TREES: buildroot-external-mender
        BUILDROOT_PATCH_DIR: "buildroot-external-mender/patches/buildroot/"
        UID: 1000
        GID: 1000
    container_name: buildroot-mender
    volumes:
      - ./:/mnt
      - buildroot-mender-ccache:/home/ccache
    environment:
      - APPLY_CONFIGS
      - CLEAN_AFTER_BUILD
      - ENV_FILES
      - EXIT_AFTER_BUILD
      - NO_BUILD
      - VERBOSE
    privileged: true
    stdin_open: true
    tty: true
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
volumes:
  buildroot-mender-ccache:
